CREATE TABLE monthly_attendance_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    year_month VARCHAR(7) NOT NULL,
    total_work_minutes INTEGER NOT NULL DEFAULT 0,
    overtime_minutes INTEGER NOT NULL DEFAULT 0,
    night_minutes INTEGER NOT NULL DEFAULT 0,
    holiday_work_minutes INTEGER NOT NULL DEFAULT 0,
    paid_leave_days DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    working_days INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_monthly_summary_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT uq_monthly_summary_employee_month UNIQUE (employee_id, year_month)
);

CREATE INDEX idx_monthly_summary_year_month ON monthly_attendance_summaries(year_month);
CREATE INDEX idx_monthly_summary_employee ON monthly_attendance_summaries(employee_id);
